[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0f766e"
backgroundColor = "#f3f6f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
